// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plain.proto

package ru.sberbank.lab2.jmhjson.protobuf;

public final class PlainProto {
  private PlainProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PlainDtoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:protobuf.PlainDto)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string field1 = 1;</code>
     * @return The field1.
     */
    String getField1();
    /**
     * <code>string field1 = 1;</code>
     * @return The bytes for field1.
     */
    com.google.protobuf.ByteString
        getField1Bytes();

    /**
     * <code>int32 field2 = 2;</code>
     * @return The field2.
     */
    int getField2();

    /**
     * <code>double field3 = 3;</code>
     * @return The field3.
     */
    double getField3();

    /**
     * <code>bool field4 = 4;</code>
     * @return The field4.
     */
    boolean getField4();
  }
  /**
   * Protobuf type {@code protobuf.PlainDto}
   */
  public static final class PlainDto extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:protobuf.PlainDto)
      PlainDtoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlainDto.newBuilder() to construct.
    private PlainDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlainDto() {
      field1_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlainDto();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return internal_static_protobuf_PlainDto_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return internal_static_protobuf_PlainDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlainProto.PlainDto.class, PlainProto.PlainDto.Builder.class);
    }

    public static final int FIELD1_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile Object field1_ = "";
    /**
     * <code>string field1 = 1;</code>
     * @return The field1.
     */
    @Override
    public String getField1() {
      Object ref = field1_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        field1_ = s;
        return s;
      }
    }
    /**
     * <code>string field1 = 1;</code>
     * @return The bytes for field1.
     */
    @Override
    public com.google.protobuf.ByteString
        getField1Bytes() {
      Object ref = field1_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        field1_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FIELD2_FIELD_NUMBER = 2;
    private int field2_ = 0;
    /**
     * <code>int32 field2 = 2;</code>
     * @return The field2.
     */
    @Override
    public int getField2() {
      return field2_;
    }

    public static final int FIELD3_FIELD_NUMBER = 3;
    private double field3_ = 0D;
    /**
     * <code>double field3 = 3;</code>
     * @return The field3.
     */
    @Override
    public double getField3() {
      return field3_;
    }

    public static final int FIELD4_FIELD_NUMBER = 4;
    private boolean field4_ = false;
    /**
     * <code>bool field4 = 4;</code>
     * @return The field4.
     */
    @Override
    public boolean getField4() {
      return field4_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(field1_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, field1_);
      }
      if (field2_ != 0) {
        output.writeInt32(2, field2_);
      }
      if (Double.doubleToRawLongBits(field3_) != 0) {
        output.writeDouble(3, field3_);
      }
      if (field4_ != false) {
        output.writeBool(4, field4_);
      }
      getUnknownFields().writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(field1_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, field1_);
      }
      if (field2_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, field2_);
      }
      if (Double.doubleToRawLongBits(field3_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, field3_);
      }
      if (field4_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, field4_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlainProto.PlainDto)) {
        return super.equals(obj);
      }
      PlainProto.PlainDto other = (PlainProto.PlainDto) obj;

      if (!getField1()
          .equals(other.getField1())) return false;
      if (getField2()
          != other.getField2()) return false;
      if (Double.doubleToLongBits(getField3())
          != Double.doubleToLongBits(
              other.getField3())) return false;
      if (getField4()
          != other.getField4()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIELD1_FIELD_NUMBER;
      hash = (53 * hash) + getField1().hashCode();
      hash = (37 * hash) + FIELD2_FIELD_NUMBER;
      hash = (53 * hash) + getField2();
      hash = (37 * hash) + FIELD3_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          Double.doubleToLongBits(getField3()));
      hash = (37 * hash) + FIELD4_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getField4());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlainProto.PlainDto parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlainProto.PlainDto parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlainProto.PlainDto parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlainProto.PlainDto parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlainProto.PlainDto parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlainProto.PlainDto parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlainProto.PlainDto parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlainProto.PlainDto parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PlainProto.PlainDto parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PlainProto.PlainDto parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlainProto.PlainDto parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlainProto.PlainDto parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlainProto.PlainDto prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code protobuf.PlainDto}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:protobuf.PlainDto)
        PlainProto.PlainDtoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return internal_static_protobuf_PlainDto_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return internal_static_protobuf_PlainDto_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlainProto.PlainDto.class, PlainProto.PlainDto.Builder.class);
      }

      // Construct using ru.sberbank.lab2.protobuf.PlainProto.PlainDto.newBuilder()
      private Builder() {

      }

      private Builder(
          BuilderParent parent) {
        super(parent);

      }
      @Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        field1_ = "";
        field2_ = 0;
        field3_ = 0D;
        field4_ = false;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return internal_static_protobuf_PlainDto_descriptor;
      }

      @Override
      public PlainProto.PlainDto getDefaultInstanceForType() {
        return getDefaultInstance();
      }

      @Override
      public PlainProto.PlainDto build() {
        PlainProto.PlainDto result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public PlainProto.PlainDto buildPartial() {
        PlainProto.PlainDto result = new PlainProto.PlainDto(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PlainProto.PlainDto result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.field1_ = field1_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.field2_ = field2_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.field3_ = field3_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.field4_ = field4_;
        }
      }

      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlainProto.PlainDto) {
          return mergeFrom((PlainProto.PlainDto)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlainProto.PlainDto other) {
        if (other == getDefaultInstance()) return this;
        if (!other.getField1().isEmpty()) {
          field1_ = other.field1_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getField2() != 0) {
          setField2(other.getField2());
        }
        if (other.getField3() != 0D) {
          setField3(other.getField3());
        }
        if (other.getField4() != false) {
          setField4(other.getField4());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                field1_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                field2_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 25: {
                field3_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 32: {
                field4_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private Object field1_ = "";
      /**
       * <code>string field1 = 1;</code>
       * @return The field1.
       */
      public String getField1() {
        Object ref = field1_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          field1_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string field1 = 1;</code>
       * @return The bytes for field1.
       */
      public com.google.protobuf.ByteString
          getField1Bytes() {
        Object ref = field1_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          field1_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string field1 = 1;</code>
       * @param value The field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1(
          String value) {
        if (value == null) { throw new NullPointerException(); }
        field1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string field1 = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearField1() {
        field1_ = getDefaultInstance().getField1();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string field1 = 1;</code>
       * @param value The bytes for field1 to set.
       * @return This builder for chaining.
       */
      public Builder setField1Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        field1_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int field2_ ;
      /**
       * <code>int32 field2 = 2;</code>
       * @return The field2.
       */
      @Override
      public int getField2() {
        return field2_;
      }
      /**
       * <code>int32 field2 = 2;</code>
       * @param value The field2 to set.
       * @return This builder for chaining.
       */
      public Builder setField2(int value) {

        field2_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 field2 = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearField2() {
        bitField0_ = (bitField0_ & ~0x00000002);
        field2_ = 0;
        onChanged();
        return this;
      }

      private double field3_ ;
      /**
       * <code>double field3 = 3;</code>
       * @return The field3.
       */
      @Override
      public double getField3() {
        return field3_;
      }
      /**
       * <code>double field3 = 3;</code>
       * @param value The field3 to set.
       * @return This builder for chaining.
       */
      public Builder setField3(double value) {

        field3_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double field3 = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearField3() {
        bitField0_ = (bitField0_ & ~0x00000004);
        field3_ = 0D;
        onChanged();
        return this;
      }

      private boolean field4_ ;
      /**
       * <code>bool field4 = 4;</code>
       * @return The field4.
       */
      @Override
      public boolean getField4() {
        return field4_;
      }
      /**
       * <code>bool field4 = 4;</code>
       * @param value The field4 to set.
       * @return This builder for chaining.
       */
      public Builder setField4(boolean value) {

        field4_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>bool field4 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearField4() {
        bitField0_ = (bitField0_ & ~0x00000008);
        field4_ = false;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:protobuf.PlainDto)
    }

    // @@protoc_insertion_point(class_scope:protobuf.PlainDto)
    private static final PlainProto.PlainDto DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlainProto.PlainDto();
    }

    public static PlainProto.PlainDto getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlainDto>
        PARSER = new com.google.protobuf.AbstractParser<PlainDto>() {
      @Override
      public PlainDto parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PlainDto> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PlainDto> getParserForType() {
      return PARSER;
    }

    @Override
    public PlainProto.PlainDto getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protobuf_PlainDto_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protobuf_PlainDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\013plain.proto\022\010protobuf\"J\n\010PlainDto\022\016\n\006f" +
      "ield1\030\001 \001(\t\022\016\n\006field2\030\002 \001(\005\022\016\n\006field3\030\003 " +
      "\001(\001\022\016\n\006field4\030\004 \001(\010B\'\n\031ru.sberbank.lab2." +
      "protobufB\nPlainProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_protobuf_PlainDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protobuf_PlainDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protobuf_PlainDto_descriptor,
        new String[] { "Field1", "Field2", "Field3", "Field4", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
